# Jekyll 기본 설정
title: MBTI 소개팅 가이드
description: MBTI로 알아보는 완벽한 소개팅 궁합과 대화 팁!
url: https://minjipi.github.io
baseurl: ""

# 빌드 설정
markdown: kramdown

# 제외할 파일
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .DS_Store
