# Jekyll 기본 설정
title: 햄스터 잡기 게임
description: 15초 안에 귀여운 햄스터를 잡아 점수를 올려보세요!
url: https://minjipi.github.io
baseurl: ""

# 테마 설정 (선택사항)
theme: jekyll-theme-minimal

#  제외할 파일 (선택사항)
exclude:
  - README.md
